language: c
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
install:
  - opam init --yes
  - opam update --yes
  - opam switch --yes $OCAML_VERSION
  - eval `opam config env`
  - opam switch
  - opam install --yes ocamlfind ocamlbuild JsOfOCairo General cairo2 menhir
  - opam upgrade --yes
  - opam list
script:
  - cd src
  - ocamlbuild -no-plugin -use-ocamlfind -menhir "menhir --table" -tag debug unit_tests.byte draw_grammar.native
  - cd ..
  - src/_build/unit_tests.byte
env:
  - OCAML_VERSION=4.02.2
  - OCAML_VERSION=4.05.0
cache:
  directories:
  - $HOME/.opam
